In [1]:
from logging import critical

import pandas as pd
import numpy as np
from scipy import stats as st

In [2]:
control = pd.read_csv("control_group.csv")
control.head()

  person_id  recovery_time_hrs
0      C001                4.4
1      C002                4.1
2      C003                3.2
3      C004                4.3
4      C005                4.9

In [3]:
test = pd.read_csv("test_group.csv")
test.head()

  person_id  recovery_time_hrs
0      T001                3.7
1      T002                4.1
2      T003                3.7
3      T004                3.9
4      T005                3.7

In [4]:
control_mean = control.recovery_time_hrs.mean()
control_std = control.recovery_time_hrs.std()
control_size = control.shape[0]

In [5]:
print(control_mean , control_size , control_std)

4.000769230769231 130 0.4795825306420972

In [6]:
test_mean = test.recovery_time_hrs.mean().round(2)
test_std = test.recovery_time_hrs.std().round(2)
test_size = test.shape[0]
test_mean,test_std,test_size

(np.float64(3.91), np.float64(0.32), 100)

In [7]:
a = control_std ** 2/control_size
b = test_std ** 2/test_size


z_score = (control_mean - test_mean)/np.sqrt(a+b)
z_score

np.float64(1.7174559340315751)

In [8]:
alpha = 0.05
critical_z_value = st.norm.ppf(1-alpha)
critical_z_value

np.float64(1.6448536269514722)

In [9]:
z_score > critical_z_value

np.True_